on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/f83585c7c0ed386a862babe8985047d8
          gist_title: Práctica-21 Comunicación UART 4550-MikroC.c
          gist_description: Prácticas MikroC Pro for PIC
          github_file: Proyecto/Comunicacion_UART/4550/SERIAL.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/7d0c2b614f231d4395f98e5cf9f915b3
          gist_title: Práctica-21 Comunicación UART 45K50-MikroC.c
          gist_description: Prácticas MikroC Pro for PIC
          github_file: Proyecto/Comunicacion_UART/45K50/SERIAL.c
          file_encoding: WINDOWS-1252
